version: '3'

services:
  db:
    image: postgres:10.1-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:3-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - 'redisdata:/data'

  pgweb:
    image: sosedoff/pgweb
    environment:
        - DATABASE_URL=postgres://postgres:postgres@db:5432?sslmode=disable
    links:
        - db
    ports:
        - "8081:8081"
    depends_on:
      - db
    restart: "on-failure:10"

  web:
    restart: unless-stopped
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/code/app
      - SERVICE_TYPE=web
    env_file:
      - app/app/local.env
    build: .
    image: 'web'
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    stdin_open: true

  celery_worker:
    image: 'web'
    env_file: 'app/app/.env'
    environment:
      - SERVICE_TYPE=worker
      - CELERY_APP=app
    volumes:
      - .:/code
    depends_on:
      - web
    entrypoint: /bin/worker.bash

  celery_beat:
    image: 'web'
    env_file: 'app/app/.env'
    environment:
      - CELERY_BEAT_ENABLED=on
      - SERVICE_TYPE=beat
      - CELERY_APP=app
    volumes:
      - .:/code
    depends_on:
      - web
    entrypoint: /bin/worker.bash

  testrpc:
    image: trufflesuite/ganache-cli
    ports:
      - "8545:8545"
    command: "-a 1 --seed 2"

  node:
    image: node:9-alpine
    working_dir: /node
    volumes:
      - .:/node
    command: bin/docker-node.sh

volumes:
  pgdata:
  redisdata:
